development:
  adapter: postgresql
  encoding: unicode
  database: A2_development
  pool: 5
  host: localhost
  username: calimero
  password: 8oomKikk&r
test:
  adapter: postgresql
  encoding: unicode
  database: A2_test
  pool: 5
  username: calimero
  password: 8oomKikk&r
staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 
